
import { Category, ImpactLevel, Region, RegulationEntry } from './types';

export const REGION_COUNTRY_MAP: Record<string, string[]> = {
  [Region.US]: ['United States', 'Canada', 'Mexico'],
  [Region.EU]: ['European Union', 'Germany', 'France', 'Italy', 'Spain', 'Netherlands', 'Switzerland', 'Belgium', 'Austria', 'Sweden', 'Norway', 'Denmark', 'Finland', 'Ireland', 'Poland'],
  [Region.APAC]: ['Japan', 'China', 'India', 'Australia', 'Singapore', 'South Korea', 'New Zealand', 'Taiwan', 'Thailand', 'Vietnam', 'Malaysia'],
  [Region.UK]: ['United Kingdom'],
  [Region.Global]: ['Global', 'WHO', 'ICH']
};

export const ALL_COUNTRIES = Array.from(new Set(Object.values(REGION_COUNTRY_MAP).flat())).sort();

// Coordinates calibrated for Equirectangular Projection (2:1 Aspect Ratio)
// Scale: X: 0-100, Y: 0-50
export const COUNTRY_COORDINATES: Record<string, { x: number; y: number }> = {
  'United States': { x: 23, y: 14.5 },
  'Canada': { x: 19, y: 9 },
  'Mexico': { x: 22, y: 18.5 },
  'United Kingdom': { x: 49.5, y: 10 },
  'European Union': { x: 52, y: 11 },
  'Germany': { x: 52.5, y: 10.8 },
  'France': { x: 50.5, y: 12.2 },
  'Italy': { x: 53, y: 13.6 },
  'Spain': { x: 49, y: 14 },
  'Netherlands': { x: 51.5, y: 10.5 },
  'Switzerland': { x: 52, y: 12 },
  'Belgium': { x: 51, y: 10.8 },
  'Austria': { x: 53.5, y: 11.8 },
  'Sweden': { x: 54, y: 7 },
  'Norway': { x: 52, y: 7 },
  'Denmark': { x: 52, y: 9 },
  'Finland': { x: 56, y: 6 },
  'Ireland': { x: 48.5, y: 10.5 },
  'Poland': { x: 55, y: 10.5 },
  'China': { x: 79, y: 15.5 },
  'India': { x: 72, y: 19 },
  'Japan': { x: 88, y: 15 },
  'Australia': { x: 87, y: 37 },
  'Singapore': { x: 78.8, y: 24.8 },
  'South Korea': { x: 85, y: 15 },
  'Taiwan': { x: 83, y: 18 },
  'Thailand': { x: 78, y: 21 },
  'Vietnam': { x: 80, y: 21 },
  'Malaysia': { x: 78, y: 23.5 },
  'New Zealand': { x: 96, y: 41 },
  'Brazil': { x: 35, y: 32 },
  'Global': { x: 45, y: 25 } // Mid-Atlantic
};

export const INITIAL_REGULATIONS: RegulationEntry[] = ([
  {
    id: '15',
    title: 'MHRA AI Airlock: Regulatory Sandbox for AI Medical Devices',
    agency: 'MHRA',
    region: Region.UK,
    country: 'United Kingdom',
    date: '2024-05-09',
    effectiveDate: '2024-05-09',
    category: Category.MedicalDevices,
    summary: 'Launch of the AI Airlock, a regulatory sandbox to assist in the safe development and deployment of AI as a Medical Device (AIaMD).',
    impact: ImpactLevel.High,
    status: 'Final',
    content: 'The AI Airlock is a collaborative regulatory sandbox designed to test and support AIaMD products in the NHS. It aims to identify and address regulatory challenges for AI devices early in the development process, fostering innovation while ensuring patient safety.',
    url: 'https://www.gov.uk/government/news/mhra-launches-ai-airlock-to-address-challenges-for-regulating-medical-devices-that-use-artificial-intelligence'
  },
  {
    id: '14',
    title: 'Implementation of Medical Device Good Manufacturing Practice (GMP) Standards',
    agency: 'NMPA',
    region: Region.APAC,
    country: 'China',
    date: '2024-04-25',
    effectiveDate: '2024-07-01',
    category: Category.Manufacturing,
    summary: 'China NMPA releases updated inspection guidelines for Medical Device GMP compliance.',
    impact: ImpactLevel.High,
    status: 'Final',
    content: 'The National Medical Products Administration (NMPA) of China has updated its GMP inspection guidelines. This includes stricter requirements for supplier management, cleanroom controls, and data integrity within the quality management system for sterile and non-sterile devices.',
    url: 'https://english.nmpa.gov.cn/'
  },
  {
    id: '13',
    title: 'General Principles of Software Validation (Final Guidance)',
    agency: 'TGA',
    region: Region.APAC,
    country: 'Australia',
    date: '2024-04-10',
    effectiveDate: '2024-04-10',
    category: Category.MedicalDevices,
    summary: 'TGA Australia guidance on software based medical devices and cyber security requirements.',
    impact: ImpactLevel.Medium,
    status: 'Final',
    content: 'This TGA guidance clarifies requirements for software as a medical device (SaMD), including classification rules, clinical evidence requirements, and cybersecurity essential principles. It aligns closely with IMDRF guidelines.',
    url: 'https://www.tga.gov.au/resources/resource/guidance/regulation-software-medical-device-guidance'
  },
  {
    id: '12',
    title: 'European Health Data Space (EHDS) Regulation Adoption',
    agency: 'EU Commission',
    region: Region.EU,
    country: 'European Union',
    date: '2024-03-24',
    effectiveDate: 'Pending',
    category: Category.Privacy,
    summary: 'New framework for sharing health data across EU borders for primary and secondary use.',
    impact: ImpactLevel.High,
    status: 'Draft',
    content: 'The EHDS aims to empower individuals to control their health data and support the use of health data for better healthcare delivery, research, innovation and policy making. It imposes strict data governance and interoperability requirements on electronic health record systems.',
    url: 'https://health.ec.europa.eu/ehealth-digital-health-and-care/european-health-data-space_en'
  },
  {
    id: '11',
    title: 'Drugs and Cosmetics (Amendment) Rules, 2024',
    agency: 'CDSCO',
    region: Region.APAC,
    country: 'India',
    date: '2024-03-12',
    effectiveDate: '2024-04-01',
    category: Category.SupplyChain,
    summary: 'India CDSCO updates import registration requirements for cosmetics and new drugs.',
    impact: ImpactLevel.Medium,
    status: 'Final',
    content: 'The amendment streamlines the online submission process for import licenses (Form 43) and introduces new fee structures for site inspections. It also clarifies the timeline for query responses during the registration process.',
    url: 'https://cdsco.gov.in/'
  },
  {
    id: '10',
    title: 'Quality Management System Regulation (QMSR) Final Rule',
    agency: 'FDA',
    region: Region.US,
    country: 'United States',
    date: '2024-02-02',
    effectiveDate: '2026-02-02',
    category: Category.Manufacturing,
    summary: 'FDA amends 21 CFR Part 820 to align with ISO 13485:2016.',
    impact: ImpactLevel.High,
    status: 'Final',
    content: 'The FDA is incorporating ISO 13485:2016 by reference into the Quality System Regulation (QSR). This move harmonizes US requirements with international standards, reducing the burden of compliance for manufacturers selling in multiple markets. The new regulation is termed the Quality Management System Regulation (QMSR).',
    url: 'https://www.federalregister.gov/documents/2024/02/02/2024-01709/medical-devices-quality-system-regulation-amendments'
  },
  {
    id: '9',
    title: 'Artificial Intelligence (AI) Act',
    agency: 'EU Commission',
    region: Region.EU,
    country: 'European Union',
    date: '2024-01-25',
    effectiveDate: 'TBD',
    category: Category.MedicalDevices,
    summary: 'Comprehensive regulation on Artificial Intelligence, classifying high-risk AI systems in healthcare.',
    impact: ImpactLevel.High,
    status: 'Final',
    content: 'The EU AI Act is the first comprehensive legal framework on AI. It classifies AI systems according to risk. High-risk AI systems, including many AI-based medical devices, will face strict conformity assessment, data governance, and transparency requirements.',
    url: 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai'
  },
  {
    id: '8',
    title: 'Sakigake Designation System for Medical Devices',
    agency: 'PMDA',
    region: Region.APAC,
    country: 'Japan',
    date: '2024-01-15',
    effectiveDate: '2024-01-15',
    category: Category.MarketAccess,
    summary: 'Japan PMDA updates criteria for expedited approval of innovative devices.',
    impact: ImpactLevel.Medium,
    status: 'Final',
    content: 'The Sakigake designation system accelerates the review of innovative medical products that satisfy certain conditions, such as severity of the disease and effectiveness of the product. Updated guidelines clarify the consultation timeline.',
    url: 'https://www.pmda.go.jp/english/'
  },
  {
    id: '7',
    title: 'Module VI – Management and reporting of adverse reactions',
    agency: 'EMA',
    region: Region.EU,
    country: 'European Union',
    date: '2024-01-10',
    effectiveDate: '2024-07-10',
    category: Category.Pharmacovigilance,
    summary: 'Updates to post-authorization safety studies and reporting requirements in GVP.',
    impact: ImpactLevel.Medium,
    status: 'Final',
    content: 'Updates regarding the validation of ICSRs and the management of duplicate cases in EudraVigilance. It clarifies the roles of the marketing authorization holder in literature monitoring and signal detection.',
    url: 'https://www.ema.europa.eu/en/human-regulatory/post-authorisation/pharmacovigilance/good-pharmacovigilance-practices'
  },
  {
    id: '6',
    title: 'Guidance for Industry: Data Integrity and Compliance with Drug CGMP',
    agency: 'FDA',
    region: Region.US,
    country: 'United States',
    date: '2023-12-15',
    effectiveDate: '2024-02-15',
    category: Category.DataIntegrity,
    summary: 'Clarifies the role of data integrity in current good manufacturing practice (CGMP) for drugs.',
    impact: ImpactLevel.High,
    status: 'Final',
    content: 'This guidance provides the FDA’s current thinking on data integrity. It emphasizes that data integrity is critical throughout the CGMP data life cycle, including creation, modification, processing, maintenance, retrieval, transmission, and disposition.',
    url: 'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/data-integrity-and-compliance-drug-cgmp-questions-and-answers'
  },
  {
    id: '5',
    title: 'Cybersecurity in Medical Devices: Quality System Considerations',
    agency: 'FDA',
    region: Region.US,
    country: 'United States',
    date: '2023-09-27',
    effectiveDate: '2023-09-27',
    category: Category.Privacy,
    summary: 'Final guidance on cybersecurity requirements for medical devices.',
    impact: ImpactLevel.High,
    status: 'Final',
    content: 'This guidance provides recommendations to industry regarding cybersecurity device design, labeling, and the documentation that FDA recommends be included in premarket submissions. It emphasizes a secure product development framework (SPDF).',
    url: 'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/cybersecurity-medical-devices-quality-system-considerations-and-content-premarket-submissions'
  },
  {
    id: '4',
    title: 'Annex 1: Manufacture of Sterile Medicinal Products',
    agency: 'EMA',
    region: Region.EU,
    country: 'European Union',
    date: '2023-08-25',
    effectiveDate: '2023-08-25',
    category: Category.Manufacturing,
    summary: 'Comprehensive revision of guidelines for sterile manufacturing, focusing on Contamination Control Strategy (CCS).',
    impact: ImpactLevel.High,
    status: 'Final',
    content: 'The revised Annex 1 provides comprehensive guidance on the manufacture of sterile products. It introduces the requirement for a holistic Contamination Control Strategy (CCS) to minimize the risk of contamination.',
    url: 'https://www.ema.europa.eu/en/human-regulatory/research-development/compliance/good-manufacturing-practice/guidance-good-manufacturing-practice'
  },
  {
    id: '3',
    title: 'ICH E6(R3) Good Clinical Practice (GCP)',
    agency: 'ICH',
    region: Region.Global,
    country: 'Global',
    date: '2023-05-19',
    effectiveDate: 'Pending Finalization',
    category: Category.ClinicalResearch,
    summary: 'Draft guideline on Good Clinical Practice aimed at modernizing clinical trial design and conduct.',
    impact: ImpactLevel.Medium,
    status: 'Draft',
    content: 'The ICH E6(R3) draft guideline addresses the evolving clinical trial landscape, including the use of digital health technologies and innovative trial designs (e.g., decentralized trials).',
    url: 'https://database.ich.org/sites/default/files/ICH_E6%28R3%29_DraftGuideline_2023_0519.pdf'
  },
  {
    id: '2',
    title: 'Agile Licensing for Drugs and Devices',
    agency: 'Health Canada',
    region: Region.US,
    country: 'Canada',
    date: '2023-04-05',
    effectiveDate: '2023-04-05',
    category: Category.RegulatorySubmissions,
    summary: 'Health Canada initiative to modernise regulatory framework for drugs and devices.',
    impact: ImpactLevel.Medium,
    status: 'Consultation',
    content: 'This initiative supports agile regulations that allow for Terms and Conditions on market authorizations and Rolling Reviews for promising therapies.',
    url: 'https://www.canada.ca/en/health-canada/services/drugs-health-products.html'
  },
  {
    id: '1',
    title: 'International Recognition Framework (IRF)',
    agency: 'MHRA',
    region: Region.UK,
    country: 'United Kingdom',
    date: '2024-05-21',
    effectiveDate: '2024-05-21',
    category: Category.MarketAccess,
    summary: 'New framework for recognizing approvals from trusted regulatory partners.',
    impact: ImpactLevel.High,
    status: 'Final',
    content: 'The MHRA has introduced the International Recognition Framework to streamline access to the UK market for medical devices and medicines that have already been approved by trusted regulators (e.g., FDA, EMA, TGA, Health Canada).',
    url: 'https://www.gov.uk/government/consultations/medical-devices-international-recognition-framework'
  }
] as RegulationEntry[]).sort((a, b) => b.date.localeCompare(a.date));
